spring:
  datasource:
    url: jdbc:mysql://inmeyu.com:8066/personManagent?characterEncoding=utf-8&useSSL=false
    username: pzy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.person.*.pojo,com.person.*.network
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl