spring:
  datasource:
    url: jdbc:mysql://inmeyu.com:3306/person_managent?characterEncoding=utf-8&useSSL=false
    username: root
    password: pzy741
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.person.*.pojo, com.person.*.network
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true