spring:
  datasource:
    url: jdbc:mysql://inmeyu.com:8066/personManagent?characterEncoding=utf-8&useSSL=false
    username: pzy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #配置测试查询语句
      validation-query: SELECT 1 FROM DUAL
      #初始化大小 最小，最大
      initial-size: 10
      min-idle: 10
      max-active: 30
      stat-view-servlet:
        #重置按钮配置
        reset-enable: true
      #配置连接在池中最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 180000
      test-on-borrow: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      #配置监控统计拦截的filters，去掉后监控界面sql无法显示,wall用于防火墙
      filters: stat, wall, log4j2
      #通过connectProperties属性打开mergeSql功能，慢sql记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  type-aliases-package: com.person
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl